version: '2'
services:
  nsmapserver:
    build:
      context: mapserver
      dockerfile: Dockerfile
    volumes:
      - ./mapserver_vol:/map
    ports:
      - "8181:80"
  map:
    build:
      context: mapcache
      dockerfile: Dockerfile
    volumes:
      - ./mapcache_vol:/map
    depends_on:
      - nsmapserver
    links:
      - nsmapserver
    ports:
      - "80"
    networks:
      - vhost_default
        